name: Upstream Sync

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    uses: aormsby/Fork-Sync-With-Upstream-action/.github/workflows/upstream-sync.yml@v3.4.1
    with:
      upstream_repository: microsoft/autogen
      upstream_branch: main
      target_branch: main
    secrets: inherit
