name: Upstream Sync

on:
  schedule:
    - cron: '0 3 * * *'          # roda diariamente 03h UTC
  workflow_dispatch:             # botão "Run workflow"

jobs:
  upstream_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Sync upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: microsoft/autogen
